export const CANVAS_FOCUS_ID = 'canvas-focus';

export const SEAT_RADIUS = 20;

export const iconTranslations = {
  "air-conditioner": "klimatyzator",
  arrow: "strzałka",
  cake: "ciasto",
  "caution-sign": "znak ostrzegawczy",
  compass: "kompas",
  "dance-area": "strefa tańca",
  "disability-sing": "znak niepełno- sprawności",
  "dj-controller": "panel didżeja",
  "electrical-outlet": "gniazdko elektryczne",
  fan: "wentylator",
  firework: "fajerwerki",
  gifts: "prezenty",
  heater: "grzejnik",
  "high-chair-sign": "znak wysokiego krzesła",
  label: "etykieta",
  "left door": "lewe drzwi",
  light: "światło",
  "long-table": "stół prostokątny",
  microphone: "mikrofon",
  pillar: "filar",
  "right-door": "prawe drzwi",
  "round-table": "stół okrągły",
  "row-of-chairs": "rząd krzeseł",
  smoke: "dym",
  sound: "dźwięk",
  "square-table": "stół kwadratowy",
  stage: "scena",
  "strainght-wall": "prosta ściana",
  target: "cel",
  tent: "namiot",
  "toilet-sign": "znak toalety",
  tree: "drzewo",
  water: "woda",
  "t-table": "stół w kształcie T",
  "u-table": "stół w kształcie U",
};
