/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const canvasWrapper: string;
declare const canvas: string;
declare const canvasOverlay: string;
declare const canvasGroup: string;
declare const canvasFocus: string;

export {
	canvasWrapper,
	canvas,
	canvasOverlay,
	canvasGroup,
	canvasFocus
};
